### ISSUE TITLE
Create README.md for basic documentation

### ISSUE THREAD

**Issue by exposy** [exposy/exposy-server#1]
Cover the following aspects in the documentation: 

- Purpose
- Benefits
- Mechanism (mention the role of [exposy/exposy-cli](https://github.com/exposy/exposy-cli))
- Development setup
- Deployment setup

**Comment by asifurrahaman754** [comment]
I can add the readme, but i need to first know the repo. can you help me with that? so u can assign it to me

**Comment by exposy** [comment]
> I can add the readme, but i need to first know the repo. can you help me with that? so u can assign it to me

@asifurrahaman754 we are drafting a Google doc around the same. That will provide the feature overview & working of this.
I will post it here & let you know. You can then create README based on the same.

**Comment by exposy** [comment]
Once the feature documentation draft will be available, will reopen this.
